# Jekyll config
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true

collections:
  content:
    output: true

# Theme
remote_theme: broccolini/swiss

# Theme config
title: Erin Dahlgren
description: Nonprofit software engineer and organizer
url: https://fun.edahlgren.com
github_username: edahlgren
theme_color: magenta
about_baseurl: /about/
serious_url: https://edahlgren.com
